// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FRAME_CALLBACK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FRAME_CALLBACK_METHOD0
typedef void (*UniffiCallbackInterfaceFrameCallbackMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FRAME_CALLBACK_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FRAME_CALLBACK_METHOD1
typedef void (*UniffiCallbackInterfaceFrameCallbackMethod1)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FRAME_CALLBACK_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FRAME_CALLBACK_METHOD2
typedef void (*UniffiCallbackInterfaceFrameCallbackMethod2)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FRAME_CALLBACK_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FRAME_CALLBACK_METHOD3
typedef void (*UniffiCallbackInterfaceFrameCallbackMethod3)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FRAME_CALLBACK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FRAME_CALLBACK
typedef struct UniffiVTableCallbackInterfaceFrameCallback {
    UniffiCallbackInterfaceFrameCallbackMethod0 _Nonnull onPreviewFrame;
    UniffiCallbackInterfaceFrameCallbackMethod1 _Nonnull onStatsUpdate;
    UniffiCallbackInterfaceFrameCallbackMethod2 _Nonnull onError;
    UniffiCallbackInterfaceFrameCallbackMethod3 _Nonnull onConnectionStatusChanged;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceFrameCallback;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_INIT_CALLBACK_VTABLE_FRAMECALLBACK
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_INIT_CALLBACK_VTABLE_FRAMECALLBACK
void uniffi_serialwarp_ffi_fn_init_callback_vtable_framecallback(UniffiVTableCallbackInterfaceFrameCallback* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_CONNECT_TRANSPORT
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_CONNECT_TRANSPORT
void uniffi_serialwarp_ffi_fn_func_connect_transport(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_CREATE_VIRTUAL_DISPLAY
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_CREATE_VIRTUAL_DISPLAY
uint32_t uniffi_serialwarp_ffi_fn_func_create_virtual_display(RustBuffer config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_DESTROY_VIRTUAL_DISPLAY
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_DESTROY_VIRTUAL_DISPLAY
void uniffi_serialwarp_ffi_fn_func_destroy_virtual_display(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_DISCONNECT_TRANSPORT
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_DISCONNECT_TRANSPORT
void uniffi_serialwarp_ffi_fn_func_disconnect_transport(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_GET_CONNECTION_STATUS
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_GET_CONNECTION_STATUS
RustBuffer uniffi_serialwarp_ffi_fn_func_get_connection_status(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_GET_DEBUG_INFO
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_GET_DEBUG_INFO
RustBuffer uniffi_serialwarp_ffi_fn_func_get_debug_info(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_GET_SETTINGS
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_GET_SETTINGS
RustBuffer uniffi_serialwarp_ffi_fn_func_get_settings(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_GET_STREAM_STATS
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_GET_STREAM_STATS
RustBuffer uniffi_serialwarp_ffi_fn_func_get_stream_stats(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_GET_VIRTUAL_DISPLAY_ID
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_GET_VIRTUAL_DISPLAY_ID
RustBuffer uniffi_serialwarp_ffi_fn_func_get_virtual_display_id(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_INIT_RUNTIME
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_INIT_RUNTIME
void uniffi_serialwarp_ffi_fn_func_init_runtime(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_IS_STREAMING
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_IS_STREAMING
int8_t uniffi_serialwarp_ffi_fn_func_is_streaming(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_LIST_CONNECTED_USB_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_LIST_CONNECTED_USB_DEVICES
RustBuffer uniffi_serialwarp_ffi_fn_func_list_connected_usb_devices(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_LIST_DISPLAYS
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_LIST_DISPLAYS
RustBuffer uniffi_serialwarp_ffi_fn_func_list_displays(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_LIST_USB_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_LIST_USB_DEVICES
RustBuffer uniffi_serialwarp_ffi_fn_func_list_usb_devices(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_SAVE_SETTINGS
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_SAVE_SETTINGS
void uniffi_serialwarp_ffi_fn_func_save_settings(RustBuffer settings, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_SHUTDOWN_RUNTIME
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_SHUTDOWN_RUNTIME
void uniffi_serialwarp_ffi_fn_func_shutdown_runtime(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_START_STREAMING
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_START_STREAMING
void uniffi_serialwarp_ffi_fn_func_start_streaming(RustBuffer config, uint64_t callback, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_STOP_STREAMING
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_FN_FUNC_STOP_STREAMING
void uniffi_serialwarp_ffi_fn_func_stop_streaming(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_serialwarp_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_serialwarp_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUSTBUFFER_FREE
void ffi_serialwarp_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_serialwarp_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_U8
void ffi_serialwarp_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_U8
void ffi_serialwarp_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_U8
void ffi_serialwarp_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_serialwarp_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_I8
void ffi_serialwarp_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_I8
void ffi_serialwarp_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_I8
void ffi_serialwarp_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_serialwarp_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_U16
void ffi_serialwarp_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_U16
void ffi_serialwarp_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_U16
void ffi_serialwarp_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_serialwarp_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_I16
void ffi_serialwarp_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_I16
void ffi_serialwarp_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_I16
void ffi_serialwarp_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_serialwarp_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_U32
void ffi_serialwarp_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_U32
void ffi_serialwarp_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_U32
void ffi_serialwarp_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_serialwarp_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_I32
void ffi_serialwarp_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_I32
void ffi_serialwarp_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_I32
void ffi_serialwarp_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_serialwarp_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_U64
void ffi_serialwarp_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_U64
void ffi_serialwarp_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_U64
void ffi_serialwarp_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_serialwarp_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_I64
void ffi_serialwarp_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_I64
void ffi_serialwarp_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_I64
void ffi_serialwarp_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_serialwarp_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_F32
void ffi_serialwarp_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_F32
void ffi_serialwarp_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_F32
void ffi_serialwarp_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_serialwarp_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_F64
void ffi_serialwarp_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_F64
void ffi_serialwarp_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_F64
void ffi_serialwarp_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_serialwarp_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_POINTER
void ffi_serialwarp_ffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_POINTER
void ffi_serialwarp_ffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_POINTER
void ffi_serialwarp_ffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_serialwarp_ffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_serialwarp_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_serialwarp_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_serialwarp_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_serialwarp_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_POLL_VOID
void ffi_serialwarp_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_serialwarp_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_FREE_VOID
void ffi_serialwarp_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_serialwarp_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_CONNECT_TRANSPORT
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_CONNECT_TRANSPORT
uint16_t uniffi_serialwarp_ffi_checksum_func_connect_transport(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_CREATE_VIRTUAL_DISPLAY
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_CREATE_VIRTUAL_DISPLAY
uint16_t uniffi_serialwarp_ffi_checksum_func_create_virtual_display(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_DESTROY_VIRTUAL_DISPLAY
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_DESTROY_VIRTUAL_DISPLAY
uint16_t uniffi_serialwarp_ffi_checksum_func_destroy_virtual_display(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_DISCONNECT_TRANSPORT
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_DISCONNECT_TRANSPORT
uint16_t uniffi_serialwarp_ffi_checksum_func_disconnect_transport(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_GET_CONNECTION_STATUS
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_GET_CONNECTION_STATUS
uint16_t uniffi_serialwarp_ffi_checksum_func_get_connection_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_GET_DEBUG_INFO
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_GET_DEBUG_INFO
uint16_t uniffi_serialwarp_ffi_checksum_func_get_debug_info(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_GET_SETTINGS
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_GET_SETTINGS
uint16_t uniffi_serialwarp_ffi_checksum_func_get_settings(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_GET_STREAM_STATS
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_GET_STREAM_STATS
uint16_t uniffi_serialwarp_ffi_checksum_func_get_stream_stats(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_GET_VIRTUAL_DISPLAY_ID
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_GET_VIRTUAL_DISPLAY_ID
uint16_t uniffi_serialwarp_ffi_checksum_func_get_virtual_display_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_INIT_RUNTIME
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_INIT_RUNTIME
uint16_t uniffi_serialwarp_ffi_checksum_func_init_runtime(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_IS_STREAMING
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_IS_STREAMING
uint16_t uniffi_serialwarp_ffi_checksum_func_is_streaming(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_LIST_CONNECTED_USB_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_LIST_CONNECTED_USB_DEVICES
uint16_t uniffi_serialwarp_ffi_checksum_func_list_connected_usb_devices(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_LIST_DISPLAYS
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_LIST_DISPLAYS
uint16_t uniffi_serialwarp_ffi_checksum_func_list_displays(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_LIST_USB_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_LIST_USB_DEVICES
uint16_t uniffi_serialwarp_ffi_checksum_func_list_usb_devices(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_SAVE_SETTINGS
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_SAVE_SETTINGS
uint16_t uniffi_serialwarp_ffi_checksum_func_save_settings(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_SHUTDOWN_RUNTIME
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_SHUTDOWN_RUNTIME
uint16_t uniffi_serialwarp_ffi_checksum_func_shutdown_runtime(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_START_STREAMING
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_START_STREAMING
uint16_t uniffi_serialwarp_ffi_checksum_func_start_streaming(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_STOP_STREAMING
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_FUNC_STOP_STREAMING
uint16_t uniffi_serialwarp_ffi_checksum_func_stop_streaming(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_METHOD_FRAMECALLBACK_ON_PREVIEW_FRAME
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_METHOD_FRAMECALLBACK_ON_PREVIEW_FRAME
uint16_t uniffi_serialwarp_ffi_checksum_method_framecallback_on_preview_frame(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_METHOD_FRAMECALLBACK_ON_STATS_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_METHOD_FRAMECALLBACK_ON_STATS_UPDATE
uint16_t uniffi_serialwarp_ffi_checksum_method_framecallback_on_stats_update(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_METHOD_FRAMECALLBACK_ON_ERROR
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_METHOD_FRAMECALLBACK_ON_ERROR
uint16_t uniffi_serialwarp_ffi_checksum_method_framecallback_on_error(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_METHOD_FRAMECALLBACK_ON_CONNECTION_STATUS_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_SERIALWARP_FFI_CHECKSUM_METHOD_FRAMECALLBACK_ON_CONNECTION_STATUS_CHANGED
uint16_t uniffi_serialwarp_ffi_checksum_method_framecallback_on_connection_status_changed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_SERIALWARP_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_serialwarp_ffi_uniffi_contract_version(void
    
);
#endif

