// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(SerialWarpFFIFFI)
import SerialWarpFFIFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_serialwarp_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_serialwarp_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * Application settings
 */
public struct AppSettings {
    public let defaultResolution: String
    public let defaultFps: UInt32
    public let defaultBitrateMbps: UInt32
    public let autoConnect: Bool
    public let previewEnabled: Bool
    public let previewQuality: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(defaultResolution: String, defaultFps: UInt32, defaultBitrateMbps: UInt32, autoConnect: Bool, previewEnabled: Bool, previewQuality: UInt32) {
        self.defaultResolution = defaultResolution
        self.defaultFps = defaultFps
        self.defaultBitrateMbps = defaultBitrateMbps
        self.autoConnect = autoConnect
        self.previewEnabled = previewEnabled
        self.previewQuality = previewQuality
    }
}



extension AppSettings: Equatable, Hashable {
    public static func ==(lhs: AppSettings, rhs: AppSettings) -> Bool {
        if lhs.defaultResolution != rhs.defaultResolution {
            return false
        }
        if lhs.defaultFps != rhs.defaultFps {
            return false
        }
        if lhs.defaultBitrateMbps != rhs.defaultBitrateMbps {
            return false
        }
        if lhs.autoConnect != rhs.autoConnect {
            return false
        }
        if lhs.previewEnabled != rhs.previewEnabled {
            return false
        }
        if lhs.previewQuality != rhs.previewQuality {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(defaultResolution)
        hasher.combine(defaultFps)
        hasher.combine(defaultBitrateMbps)
        hasher.combine(autoConnect)
        hasher.combine(previewEnabled)
        hasher.combine(previewQuality)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAppSettings: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AppSettings {
        return
            try AppSettings(
                defaultResolution: FfiConverterString.read(from: &buf), 
                defaultFps: FfiConverterUInt32.read(from: &buf), 
                defaultBitrateMbps: FfiConverterUInt32.read(from: &buf), 
                autoConnect: FfiConverterBool.read(from: &buf), 
                previewEnabled: FfiConverterBool.read(from: &buf), 
                previewQuality: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: AppSettings, into buf: inout [UInt8]) {
        FfiConverterString.write(value.defaultResolution, into: &buf)
        FfiConverterUInt32.write(value.defaultFps, into: &buf)
        FfiConverterUInt32.write(value.defaultBitrateMbps, into: &buf)
        FfiConverterBool.write(value.autoConnect, into: &buf)
        FfiConverterBool.write(value.previewEnabled, into: &buf)
        FfiConverterUInt32.write(value.previewQuality, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppSettings_lift(_ buf: RustBuffer) throws -> AppSettings {
    return try FfiConverterTypeAppSettings.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppSettings_lower(_ value: AppSettings) -> RustBuffer {
    return FfiConverterTypeAppSettings.lower(value)
}


/**
 * Debug information
 */
public struct DebugInfo {
    public let connectedDevices: [UsbDeviceInfo]
    public let supportedDevices: [UsbDeviceInfo]
    public let lastError: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(connectedDevices: [UsbDeviceInfo], supportedDevices: [UsbDeviceInfo], lastError: String?) {
        self.connectedDevices = connectedDevices
        self.supportedDevices = supportedDevices
        self.lastError = lastError
    }
}



extension DebugInfo: Equatable, Hashable {
    public static func ==(lhs: DebugInfo, rhs: DebugInfo) -> Bool {
        if lhs.connectedDevices != rhs.connectedDevices {
            return false
        }
        if lhs.supportedDevices != rhs.supportedDevices {
            return false
        }
        if lhs.lastError != rhs.lastError {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(connectedDevices)
        hasher.combine(supportedDevices)
        hasher.combine(lastError)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDebugInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DebugInfo {
        return
            try DebugInfo(
                connectedDevices: FfiConverterSequenceTypeUsbDeviceInfo.read(from: &buf), 
                supportedDevices: FfiConverterSequenceTypeUsbDeviceInfo.read(from: &buf), 
                lastError: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: DebugInfo, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeUsbDeviceInfo.write(value.connectedDevices, into: &buf)
        FfiConverterSequenceTypeUsbDeviceInfo.write(value.supportedDevices, into: &buf)
        FfiConverterOptionString.write(value.lastError, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDebugInfo_lift(_ buf: RustBuffer) throws -> DebugInfo {
    return try FfiConverterTypeDebugInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDebugInfo_lower(_ value: DebugInfo) -> RustBuffer {
    return FfiConverterTypeDebugInfo.lower(value)
}


/**
 * Display information
 */
public struct DisplayInfo {
    public let id: UInt32
    public let name: String
    public let width: UInt32
    public let height: UInt32
    public let isMain: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: UInt32, name: String, width: UInt32, height: UInt32, isMain: Bool) {
        self.id = id
        self.name = name
        self.width = width
        self.height = height
        self.isMain = isMain
    }
}



extension DisplayInfo: Equatable, Hashable {
    public static func ==(lhs: DisplayInfo, rhs: DisplayInfo) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        if lhs.isMain != rhs.isMain {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(width)
        hasher.combine(height)
        hasher.combine(isMain)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDisplayInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DisplayInfo {
        return
            try DisplayInfo(
                id: FfiConverterUInt32.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                width: FfiConverterUInt32.read(from: &buf), 
                height: FfiConverterUInt32.read(from: &buf), 
                isMain: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: DisplayInfo, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterUInt32.write(value.width, into: &buf)
        FfiConverterUInt32.write(value.height, into: &buf)
        FfiConverterBool.write(value.isMain, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDisplayInfo_lift(_ buf: RustBuffer) throws -> DisplayInfo {
    return try FfiConverterTypeDisplayInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDisplayInfo_lower(_ value: DisplayInfo) -> RustBuffer {
    return FfiConverterTypeDisplayInfo.lower(value)
}


/**
 * Preview frame data
 */
public struct PreviewFrame {
    public let data: Data
    public let width: UInt32
    public let height: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(data: Data, width: UInt32, height: UInt32) {
        self.data = data
        self.width = width
        self.height = height
    }
}



extension PreviewFrame: Equatable, Hashable {
    public static func ==(lhs: PreviewFrame, rhs: PreviewFrame) -> Bool {
        if lhs.data != rhs.data {
            return false
        }
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(data)
        hasher.combine(width)
        hasher.combine(height)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePreviewFrame: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PreviewFrame {
        return
            try PreviewFrame(
                data: FfiConverterData.read(from: &buf), 
                width: FfiConverterUInt32.read(from: &buf), 
                height: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: PreviewFrame, into buf: inout [UInt8]) {
        FfiConverterData.write(value.data, into: &buf)
        FfiConverterUInt32.write(value.width, into: &buf)
        FfiConverterUInt32.write(value.height, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreviewFrame_lift(_ buf: RustBuffer) throws -> PreviewFrame {
    return try FfiConverterTypePreviewFrame.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreviewFrame_lower(_ value: PreviewFrame) -> RustBuffer {
    return FfiConverterTypePreviewFrame.lower(value)
}


/**
 * Stream configuration
 */
public struct StreamConfig {
    public let width: UInt32
    public let height: UInt32
    public let fps: UInt32
    public let bitrateMbps: UInt32
    public let hidpi: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(width: UInt32, height: UInt32, fps: UInt32, bitrateMbps: UInt32, hidpi: Bool) {
        self.width = width
        self.height = height
        self.fps = fps
        self.bitrateMbps = bitrateMbps
        self.hidpi = hidpi
    }
}



extension StreamConfig: Equatable, Hashable {
    public static func ==(lhs: StreamConfig, rhs: StreamConfig) -> Bool {
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        if lhs.fps != rhs.fps {
            return false
        }
        if lhs.bitrateMbps != rhs.bitrateMbps {
            return false
        }
        if lhs.hidpi != rhs.hidpi {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(width)
        hasher.combine(height)
        hasher.combine(fps)
        hasher.combine(bitrateMbps)
        hasher.combine(hidpi)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStreamConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StreamConfig {
        return
            try StreamConfig(
                width: FfiConverterUInt32.read(from: &buf), 
                height: FfiConverterUInt32.read(from: &buf), 
                fps: FfiConverterUInt32.read(from: &buf), 
                bitrateMbps: FfiConverterUInt32.read(from: &buf), 
                hidpi: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: StreamConfig, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.width, into: &buf)
        FfiConverterUInt32.write(value.height, into: &buf)
        FfiConverterUInt32.write(value.fps, into: &buf)
        FfiConverterUInt32.write(value.bitrateMbps, into: &buf)
        FfiConverterBool.write(value.hidpi, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamConfig_lift(_ buf: RustBuffer) throws -> StreamConfig {
    return try FfiConverterTypeStreamConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamConfig_lower(_ value: StreamConfig) -> RustBuffer {
    return FfiConverterTypeStreamConfig.lower(value)
}


/**
 * Streaming statistics
 */
public struct StreamStats {
    public let fps: Double
    public let bitrateBps: UInt64
    public let framesCaptured: UInt64
    public let framesEncoded: UInt64
    public let framesSent: UInt64
    public let framesDropped: UInt64
    public let elapsedSeconds: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(fps: Double, bitrateBps: UInt64, framesCaptured: UInt64, framesEncoded: UInt64, framesSent: UInt64, framesDropped: UInt64, elapsedSeconds: Double) {
        self.fps = fps
        self.bitrateBps = bitrateBps
        self.framesCaptured = framesCaptured
        self.framesEncoded = framesEncoded
        self.framesSent = framesSent
        self.framesDropped = framesDropped
        self.elapsedSeconds = elapsedSeconds
    }
}



extension StreamStats: Equatable, Hashable {
    public static func ==(lhs: StreamStats, rhs: StreamStats) -> Bool {
        if lhs.fps != rhs.fps {
            return false
        }
        if lhs.bitrateBps != rhs.bitrateBps {
            return false
        }
        if lhs.framesCaptured != rhs.framesCaptured {
            return false
        }
        if lhs.framesEncoded != rhs.framesEncoded {
            return false
        }
        if lhs.framesSent != rhs.framesSent {
            return false
        }
        if lhs.framesDropped != rhs.framesDropped {
            return false
        }
        if lhs.elapsedSeconds != rhs.elapsedSeconds {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(fps)
        hasher.combine(bitrateBps)
        hasher.combine(framesCaptured)
        hasher.combine(framesEncoded)
        hasher.combine(framesSent)
        hasher.combine(framesDropped)
        hasher.combine(elapsedSeconds)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStreamStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StreamStats {
        return
            try StreamStats(
                fps: FfiConverterDouble.read(from: &buf), 
                bitrateBps: FfiConverterUInt64.read(from: &buf), 
                framesCaptured: FfiConverterUInt64.read(from: &buf), 
                framesEncoded: FfiConverterUInt64.read(from: &buf), 
                framesSent: FfiConverterUInt64.read(from: &buf), 
                framesDropped: FfiConverterUInt64.read(from: &buf), 
                elapsedSeconds: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: StreamStats, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.fps, into: &buf)
        FfiConverterUInt64.write(value.bitrateBps, into: &buf)
        FfiConverterUInt64.write(value.framesCaptured, into: &buf)
        FfiConverterUInt64.write(value.framesEncoded, into: &buf)
        FfiConverterUInt64.write(value.framesSent, into: &buf)
        FfiConverterUInt64.write(value.framesDropped, into: &buf)
        FfiConverterDouble.write(value.elapsedSeconds, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamStats_lift(_ buf: RustBuffer) throws -> StreamStats {
    return try FfiConverterTypeStreamStats.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamStats_lower(_ value: StreamStats) -> RustBuffer {
    return FfiConverterTypeStreamStats.lower(value)
}


/**
 * USB device information
 */
public struct UsbDeviceInfo {
    public let name: String
    public let vendorId: UInt16
    public let productId: UInt16

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, vendorId: UInt16, productId: UInt16) {
        self.name = name
        self.vendorId = vendorId
        self.productId = productId
    }
}



extension UsbDeviceInfo: Equatable, Hashable {
    public static func ==(lhs: UsbDeviceInfo, rhs: UsbDeviceInfo) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.vendorId != rhs.vendorId {
            return false
        }
        if lhs.productId != rhs.productId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(vendorId)
        hasher.combine(productId)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUsbDeviceInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UsbDeviceInfo {
        return
            try UsbDeviceInfo(
                name: FfiConverterString.read(from: &buf), 
                vendorId: FfiConverterUInt16.read(from: &buf), 
                productId: FfiConverterUInt16.read(from: &buf)
        )
    }

    public static func write(_ value: UsbDeviceInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterUInt16.write(value.vendorId, into: &buf)
        FfiConverterUInt16.write(value.productId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsbDeviceInfo_lift(_ buf: RustBuffer) throws -> UsbDeviceInfo {
    return try FfiConverterTypeUsbDeviceInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsbDeviceInfo_lower(_ value: UsbDeviceInfo) -> RustBuffer {
    return FfiConverterTypeUsbDeviceInfo.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Connection status enum
 */

public enum ConnectionStatus {
    
    case disconnected
    case connecting
    case connected
    case streaming
    case error
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectionStatus: FfiConverterRustBuffer {
    typealias SwiftType = ConnectionStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectionStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .disconnected
        
        case 2: return .connecting
        
        case 3: return .connected
        
        case 4: return .streaming
        
        case 5: return .error
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ConnectionStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .disconnected:
            writeInt(&buf, Int32(1))
        
        
        case .connecting:
            writeInt(&buf, Int32(2))
        
        
        case .connected:
            writeInt(&buf, Int32(3))
        
        
        case .streaming:
            writeInt(&buf, Int32(4))
        
        
        case .error:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionStatus_lift(_ buf: RustBuffer) throws -> ConnectionStatus {
    return try FfiConverterTypeConnectionStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionStatus_lower(_ value: ConnectionStatus) -> RustBuffer {
    return FfiConverterTypeConnectionStatus.lower(value)
}



extension ConnectionStatus: Equatable, Hashable {}




/**
 * FFI error type
 */
public enum FfiError {

    
    
    case DeviceNotFound
    case ConnectionFailed(msg: String
    )
    case AlreadyConnected
    case NotConnected
    case DisplayCreationFailed(msg: String
    )
    case DisplayNotFound
    case CapturePermissionDenied
    case StreamCreationFailed(msg: String
    )
    case EncoderCreationFailed(msg: String
    )
    case AlreadyStreaming
    case NotStreaming
    case RuntimeNotInitialized
    case InternalError(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .DeviceNotFound
        case 2: return .ConnectionFailed(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .AlreadyConnected
        case 4: return .NotConnected
        case 5: return .DisplayCreationFailed(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 6: return .DisplayNotFound
        case 7: return .CapturePermissionDenied
        case 8: return .StreamCreationFailed(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 9: return .EncoderCreationFailed(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 10: return .AlreadyStreaming
        case 11: return .NotStreaming
        case 12: return .RuntimeNotInitialized
        case 13: return .InternalError(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .DeviceNotFound:
            writeInt(&buf, Int32(1))
        
        
        case let .ConnectionFailed(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case .AlreadyConnected:
            writeInt(&buf, Int32(3))
        
        
        case .NotConnected:
            writeInt(&buf, Int32(4))
        
        
        case let .DisplayCreationFailed(msg):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(msg, into: &buf)
            
        
        case .DisplayNotFound:
            writeInt(&buf, Int32(6))
        
        
        case .CapturePermissionDenied:
            writeInt(&buf, Int32(7))
        
        
        case let .StreamCreationFailed(msg):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .EncoderCreationFailed(msg):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(msg, into: &buf)
            
        
        case .AlreadyStreaming:
            writeInt(&buf, Int32(10))
        
        
        case .NotStreaming:
            writeInt(&buf, Int32(11))
        
        
        case .RuntimeNotInitialized:
            writeInt(&buf, Int32(12))
        
        
        case let .InternalError(msg):
            writeInt(&buf, Int32(13))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


extension FfiError: Equatable, Hashable {}

extension FfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




/**
 * Callback interface for streaming events
 * Implemented by Swift code and called from Rust
 */
public protocol FrameCallback : AnyObject {
    
    /**
     * Called when a new preview frame is available
     */
    func onPreviewFrame(frame: PreviewFrame) 
    
    /**
     * Called when stats are updated
     */
    func onStatsUpdate(stats: StreamStats) 
    
    /**
     * Called when an error occurs
     */
    func onError(message: String) 
    
    /**
     * Called when connection status changes
     */
    func onConnectionStatusChanged(status: ConnectionStatus) 
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceFrameCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceFrameCallback = UniffiVTableCallbackInterfaceFrameCallback(
        onPreviewFrame: { (
            uniffiHandle: UInt64,
            frame: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFrameCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onPreviewFrame(
                     frame: try FfiConverterTypePreviewFrame.lift(frame)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onStatsUpdate: { (
            uniffiHandle: UInt64,
            stats: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFrameCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onStatsUpdate(
                     stats: try FfiConverterTypeStreamStats.lift(stats)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onError: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFrameCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onError(
                     message: try FfiConverterString.lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onConnectionStatusChanged: { (
            uniffiHandle: UInt64,
            status: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFrameCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onConnectionStatusChanged(
                     status: try FfiConverterTypeConnectionStatus.lift(status)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceFrameCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface FrameCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitFrameCallback() {
    uniffi_serialwarp_ffi_fn_init_callback_vtable_framecallback(&UniffiCallbackInterfaceFrameCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceFrameCallback {
    fileprivate static var handleMap = UniffiHandleMap<FrameCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceFrameCallback : FfiConverter {
    typealias SwiftType = FrameCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDisplayInfo: FfiConverterRustBuffer {
    typealias SwiftType = [DisplayInfo]

    public static func write(_ value: [DisplayInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDisplayInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DisplayInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [DisplayInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDisplayInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeUsbDeviceInfo: FfiConverterRustBuffer {
    typealias SwiftType = [UsbDeviceInfo]

    public static func write(_ value: [UsbDeviceInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeUsbDeviceInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UsbDeviceInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [UsbDeviceInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeUsbDeviceInfo.read(from: &buf))
        }
        return seq
    }
}
/**
 * Connect to the USB transport
 */
public func connectTransport()throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_serialwarp_ffi_fn_func_connect_transport($0
    )
}
}
/**
 * Create a virtual display with the given configuration
 */
public func createVirtualDisplay(config: StreamConfig)throws  -> UInt32 {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_serialwarp_ffi_fn_func_create_virtual_display(
        FfiConverterTypeStreamConfig.lower(config),$0
    )
})
}
/**
 * Destroy the virtual display
 */
public func destroyVirtualDisplay() {try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_destroy_virtual_display($0
    )
}
}
/**
 * Disconnect from the USB transport
 */
public func disconnectTransport() {try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_disconnect_transport($0
    )
}
}
/**
 * Get current connection status
 */
public func getConnectionStatus() -> ConnectionStatus {
    return try!  FfiConverterTypeConnectionStatus.lift(try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_get_connection_status($0
    )
})
}
/**
 * Get debug information
 */
public func getDebugInfo() -> DebugInfo {
    return try!  FfiConverterTypeDebugInfo.lift(try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_get_debug_info($0
    )
})
}
/**
 * Get application settings
 */
public func getSettings() -> AppSettings {
    return try!  FfiConverterTypeAppSettings.lift(try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_get_settings($0
    )
})
}
/**
 * Get current stream statistics
 */
public func getStreamStats() -> StreamStats {
    return try!  FfiConverterTypeStreamStats.lift(try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_get_stream_stats($0
    )
})
}
/**
 * Get the current virtual display ID
 */
public func getVirtualDisplayId() -> UInt32? {
    return try!  FfiConverterOptionUInt32.lift(try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_get_virtual_display_id($0
    )
})
}
/**
 * Initialize the async runtime. Call this at app startup.
 */
public func initRuntime() {try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_init_runtime($0
    )
}
}
/**
 * Check if currently streaming
 */
public func isStreaming() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_is_streaming($0
    )
})
}
/**
 * List connected USB devices
 */
public func listConnectedUsbDevices() -> [UsbDeviceInfo] {
    return try!  FfiConverterSequenceTypeUsbDeviceInfo.lift(try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_list_connected_usb_devices($0
    )
})
}
/**
 * List available displays on the system
 */
public func listDisplays() -> [DisplayInfo] {
    return try!  FfiConverterSequenceTypeDisplayInfo.lift(try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_list_displays($0
    )
})
}
/**
 * List supported USB devices
 */
public func listUsbDevices() -> [UsbDeviceInfo] {
    return try!  FfiConverterSequenceTypeUsbDeviceInfo.lift(try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_list_usb_devices($0
    )
})
}
/**
 * Save application settings
 */
public func saveSettings(settings: AppSettings) {try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_save_settings(
        FfiConverterTypeAppSettings.lower(settings),$0
    )
}
}
/**
 * Shutdown the async runtime. Call this at app termination.
 */
public func shutdownRuntime() {try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_shutdown_runtime($0
    )
}
}
/**
 * Start streaming with the given configuration and callback
 */
public func startStreaming(config: StreamConfig, callback: FrameCallback)throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_serialwarp_ffi_fn_func_start_streaming(
        FfiConverterTypeStreamConfig.lower(config),
        FfiConverterCallbackInterfaceFrameCallback.lower(callback),$0
    )
}
}
/**
 * Stop streaming
 */
public func stopStreaming() {try! rustCall() {
    uniffi_serialwarp_ffi_fn_func_stop_streaming($0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_serialwarp_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_connect_transport() != 60416) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_create_virtual_display() != 46319) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_destroy_virtual_display() != 60499) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_disconnect_transport() != 28044) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_get_connection_status() != 23117) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_get_debug_info() != 2013) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_get_settings() != 13007) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_get_stream_stats() != 16501) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_get_virtual_display_id() != 33532) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_init_runtime() != 54055) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_is_streaming() != 1541) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_list_connected_usb_devices() != 62748) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_list_displays() != 54490) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_list_usb_devices() != 62746) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_save_settings() != 27739) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_shutdown_runtime() != 3724) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_start_streaming() != 17901) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_func_stop_streaming() != 58144) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_method_framecallback_on_preview_frame() != 51549) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_method_framecallback_on_stats_update() != 22812) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_method_framecallback_on_error() != 64617) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_serialwarp_ffi_checksum_method_framecallback_on_connection_status_changed() != 56496) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitFrameCallback()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all